# Generated by Django 6.0 on 2026-01-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('joining_date', models.DateField(blank=True, db_column='joining_date', null=True)),
            ],
            options={
                'verbose_name': 'Telegram用户',
                'verbose_name_plural': 'Telegram用户',
                'db_table': 'telegram_users',
            },
        ),
    ]
